### ISSUE TITLE
pyreadline crashes when importing pip

### ISSUE THREAD

**Issue by pfmoore** [pyreadline/pyreadline#18]
To reproduce:
1. Install the development version of pip, and pyreadline
2. Start an interactive prompt.
3. import pip

The crash is in pyreadline - here is a part of the (infinite) traceback:

```
Readline internal error
Traceback (most recent call last):
  File "C:\Utils\Python\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Utils\Python\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "C:\Utils\Python\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
Traceback (most recent call last):
  File "C:\Utils\Python\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Utils\Python\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "C:\Utils\Python\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
  File "C:\Utils\Python\lib\site-packages\pyreadline\rlmain.py", line 466, in _print_prompt
    x, y = c.pos()
  File "C:\Utils\Python\lib\site-packages\pyreadline\console\console.py", line 261, in pos
    self.GetConsoleScreenBufferInfo(self.hout, byref(info))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_CONSOLE_SCREEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO
```

At a minimum, some way of disabling pyreadline would be useful so that users can workaround this issue. At the moment, if pyreadline causes problems like this, the only solution is to uninstall it.

**Comment by nitrocode** [comment]
I'm using colorama==0.3.7 and pyreadline==2.1. I saw this while running my suite of pytests and it's very difficult for me to reproduce this as running the entire suite causes the issue and running the individual test seems to work...

Here is my infinite error message:

```
Readline internal error
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 569, in readline
    self.readline_setup(prompt)
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 565, in readline_setup
    self._print_prompt()
  File "c:\python27\lib\site-packages\pyreadline\rlmain.py", line 468, in _print_prompt
    n = c.write_scrolling(self.prompt, self.prompt_color)
  File "c:\python27\lib\site-packages\pyreadline\console\console.py", line 322, in write_scrolling
    w, h = self.size()
TypeError: 'NoneType' object is not iterable
```

Has anyone else seen this?

Edit: Removing pytest's --pdb flag is a workaround for now
