### ISSUE TITLE
AttributeError: 'module' object has no attribute 'logger'

### ISSUE THREAD

**Issue by ionelmc** [pyreadline/pyreadline#33]
```
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "/home/ionel/osp/python-remote-pdb/tests/test_remote_pdb.py", line 99, in <module>
    func_a()
  File "/home/ionel/osp/python-remote-pdb/tests/test_remote_pdb.py", line 84, in func_a
    func_b(patch_stdstreams)
  File "/home/ionel/osp/python-remote-pdb/tests/test_remote_pdb.py", line 78, in func_b
    set_trace(patch_stdstreams=patch_stdstreams)
  File "/home/ionel/osp/python-remote-pdb/src/remote_pdb.py", line 125, in set_trace
    rdb = RemotePdb(host=host, port=port, patch_stdstreams=patch_stdstreams)
  File "/home/ionel/osp/python-remote-pdb/src/remote_pdb.py", line 74, in __init__
    Pdb.__init__(self, completekey='tab', stdin=self.handle, stdout=self.handle)
  File "/home/ionel/osp/python-remote-pdb/.env/pypy-nocover-pdbpp/site-packages/pdb.py", line 204, in __init__
    pdb.Pdb.__init__(self, *args, **kwds)
  File "/usr/lib/pypy/lib-python/2.7/pdb.py", line 72, in __init__
    import readline
  File "/home/ionel/osp/python-remote-pdb/.env/pypy-nocover-pdbpp/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/home/ionel/osp/python-remote-pdb/.env/pypy-nocover-pdbpp/site-packages/pyreadline/__init__.py", line 11, in <module>
    from . import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "/home/ionel/osp/python-remote-pdb/.env/pypy-nocover-pdbpp/site-packages/pyreadline/modes/__init__.py", line 3, in <module>
    from . import emacs, notemacs, vi
  File "/home/ionel/osp/python-remote-pdb/.env/pypy-nocover-pdbpp/site-packages/pyreadline/modes/emacs.py", line 11, in <module>
    import pyreadline.logger as logger
AttributeError: 'module' object has no attribute 'logger'
```

**Comment by ionelmc** [comment]
Looks like we have a circular import issue here
