### ISSUE TITLE
.python_history file decoding error when it has non-ascii char

### ISSUE THREAD

**Issue by grizlupo** [pyreadline/pyreadline#54]
windows 10
pyreadline (2.1)
python 3.6.1

history.py:82
            for line in open(filename, 'r'):
                self.add_history(lineobj.ReadLineTextBuffer(ensure_unicode(line.rstrip())))

Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site.py", line 418, in register_readline
    readline.read_history_file(history)
  File "C:\Program Files\Python36\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "C:\Program Files\Python36\lib\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 615: illegal multibyte sequence
>>>

history.py:82
            for line in open(filename, 'rb'):  # <- binary mode
                self.add_history(lineobj.ReadLineTextBuffer(ensure_unicode(line.rstrip())))

Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

ok!

**Comment by Notmeor** [comment]
Same here. Any advice?

**Comment by gotoh** [comment]
Fix it please.
I'm waiting for long time...

``` diff
--- c:/Python37/Lib/site-packages/pyreadline/lineeditor/history.py	2020-09-03 19:12:33.340018500 +0900
+++ c:/Python37/Lib/site-packages/pyreadline/lineeditor/history.py	2020-09-03 19:12:36.726706300 +0900
@@ -8,7 +8,7 @@
 from __future__ import print_function, unicode_literals, absolute_import
 import re, operator, string, sys, os
 
-from pyreadline.unicode_helper import ensure_unicode, ensure_str
+from pyreadline.unicode_helper import ensure_unicode, ensure_str, pyreadline_codepage
 if "pyreadline" in sys.modules:
     pyreadline = sys.modules["pyreadline"]
 else:
@@ -79,7 +79,7 @@
         if filename is None:
             filename = self.history_filename
         try:
-            for line in open(filename, 'r'):
+            for line in open(filename, 'r', encoding=pyreadline_codepage):
                 self.add_history(lineobj.ReadLineTextBuffer(ensure_unicode(line.rstrip())))
         except IOError:
             self.history = []
```
