### ISSUE TITLE
python.exe on Windows 10 with Python 3.10 errors after this module is installed

### ISSUE THREAD

**Issue by keeely** [pyreadline/pyreadline#73]
After installing, the python executable errors when run interactively.  When I uninstalled pyreadline it stopped.

**Comment by keeely** [comment]
![image](https://user-images.githubusercontent.com/11296296/142420203-562a07a5-13c6-402c-b95f-6fd561477810.png)

**Comment by keeely** [comment]
FYI, see also: https://bugs.python.org/issue45870

**Comment by liyiliuxingyu** [comment]
Please see this link https://github.com/hylang/hy/issues/2114#issuecomment-950864067.

**Comment by liyiliuxingyu** [comment]
Please change the code in line 8 of "c:\python\lib\site-packages\pyreadline\py3k_compat.py" to return isinstance(x, collections.abc.Callable), so that it can run successfully.

**Comment by liyiliuxingyu** [comment]
Hopefully, the developer will fix the bug

**Comment by duanqn** [comment]
Also hit this issue. Would be nice if someone can fix it.

**Comment by andy-maier** [comment]
I have the same problem, see https://github.com/zhmcclient/zhmccli/runs/4498710188?check_suite_focus=true.

**Comment by keeely** [comment]
> Please change the code in line 8 of "c:\python\lib\site-packages\pyreadline\py3k_compat.py" to return isinstance(x, collections.abc.Callable), so that it can run successfully.

Can you create a PR?  I deleted the Windows VM I tested this on as I gave up supporting Windows because of this, so I can't easily test such a change.  Did you test that on older versions of Python that pyreadline is supposed to support?

**Comment by eabase** [comment]
@liyiliuxingyu
Changing the code as suggested doesn't completely fix it.
It just removes one of the errors, and breaks other things.

**Comment by eabase** [comment]
In powershell:

Before edit:
```bash
 $ python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Python310\lib\site.py", line 446, in register_readline
    import readline
  File "C:\Python310\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Python310\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Python310\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Python310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

after suggested edit in `cd C:\Python310\Lib\site-packages\pyreadline\`:

```bash
 $ python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> if (1):
... <I hit a TAB here>

Readline internal error
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "C:\Python310\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "C:\Python310\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "C:\Python310\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "C:\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "C:\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "C:\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "C:\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "C:\Python310\lib\rlcompleter.py", line 81, in complete
    readline.redisplay()
AttributeError: module 'readline' has no attribute 'redisplay'
  File "<stdin>", line 2

    ^
IndentationError: expected an indented block after 'if' statement on line 1
```

**Comment by eabase** [comment]
@keeely
In addition to the fix above, you also need to fix this:

You need to edit: `C:\Python310\Lib\site-packages\pyreadline\modes\basemode.py`:
Adding the code as shown in #64:
```python
# at line 196
        if (len(text) == 0):
            return

# at line ~272
        self.insert_text('    ')
```
Other related issues:
#70 
#49 

@liyiliuxingyu
With these 2 sets of changes it now works great!

**Comment by liyiliuxingyu** [comment]
> Changing the code as suggested doesn't fix it!
> It just removes one of the errors, and breaks other things.

    @eabase Thanks. That's great.

**Comment by eabase** [comment]
Having used this *hack* for a while, I am still unhappy. Command completion seem to fail, and instead of "just failing", it 
1. places the 4 spaces `'    '` and you need to hit backspace 4 times to get back where you were. 
2. duplicates the completion output for some unknown reason.

![image](https://user-images.githubusercontent.com/52289379/149437069-cb418c18-bbcb-4adb-be19-f5574aec13da.png)

Typing this:
![image](https://user-images.githubusercontent.com/52289379/149437531-49ca69b9-cd36-4d58-b2e7-3d17cd7eb724.png)

Then hitting TAB once, give me this:
![image](https://user-images.githubusercontent.com/52289379/149437560-2f0b9bcb-7559-4f7d-9785-20573192d0d1.png)

(Using *pwsh.exe* `7.2.1` in *Windows Terminal*.)

---

Seem like there is a hack in #71 
`    #Override completer from rlcompleter to disable automatic ( on callable`

**Comment by eabase** [comment]
The above and the following enabling VT like this: 
```
Type              : ConsoleHost
OutputEncoding    : Unicode (UTF-8)
Registry VT Level : 1
CodePage (input)  : 65001
CodePage (output) : 65001
ConInMode         : 0xf7
ConOutMode        : 0x7
```

Seem to have fixed the issue

**Comment by Ghoreish** [comment]
Dears,

I suggest you use the following command to solve the problem:
> python -m pip install --upgrade pyreadline3
or:
> pip install --upgrade pyreadline3
or:
> python -m pip install pyreadline3
