### ISSUE TITLE
Code error in pyreadline/keysyms/__init__.py

### ISSUE THREAD

**Issue by myronwalkersonos** [pyreadline/pyreadline#74]
The code in pyreadline/keysyms/__init__.py raises the following exception on linux.

```
Traceback (most recent call last):
  File "../.venv/bin/sphinx-apidoc", line 5, in <module>
    from sphinx.ext.apidoc import main
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/sphinx/ext/apidoc.py", line 30, in <module>
    from sphinx.cmd.quickstart import EXTENSIONS
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/sphinx/cmd/quickstart.py", line 22, in <module>
    import readline
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
    from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
  File "/media/myron/SSD/source/projects/sonos-qa/automation/.venv/lib/python3.8/site-packages/pyreadline/keysyms/__init__.py", line 28, in <module>
    raise ImportError("Could not import keysym for local pythonversion", x)
NameError: name 'x' is not defined
```
This prevents the code from raising the proper ImportError indicating the modules which are attempting to be loaded are not available on linux.   The issue here is that the code assumes that 

```python
except ImportError as x:
```

WIll assign a value to 'x'.  It does not.  To fix this issue you create a variable and assign x to it.

```python
raised_x = None
try:
      blah
except Exception as x:
      raised_x = x

if not success:
    raise ImportError("Could not import keysym for local pythonversion", raised_x)
```
This fixes the issue and the proper ImportError is again raised.

**Comment by eabase** [comment]
@myronsonos  
How do you reproduce this error?
Have you checked if this is still happening in pyreadline3 ?

**Comment by myronwalkersonos** [comment]
So, I produced this error by installing the package and then running sphinx-apidoc.  This was run on python3.8 and a key element of this is that it occurs on Linux
