### ISSUE TITLE
`UnicodeDecodeError` after using sympy's math expressions?

### ISSUE THREAD

**Issue by adhxtry** [pyreadline/pyreadline#77]
## Full Traceback:
```cmd
C:\windows\system32>python
```
```py
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Program Files\Python\Python39\lib\site.py", line 449, in register_readline
    readline.read_history_file(history)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
  File "C:\Program Files\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 21: character maps to <undefined>
>>>
```

## How I got into this? (Maybe steps to reproduce)

1. First open python shell with `python` command in cmd.
2. Import sympy and call `init_session()` and `init_printing()` function. (Here in example I am calling only `init_printing` because the `init_session` command was giving me the same error).
3. Print some beautiful math expressions.
4. Close the shell with `exit()` and reopen python shell.

```py
>>> from sympy import *
>>>
>>> init_printing()
>>> Integral((x:=Symbol('x'))**2,x)
⌠
⎮  2
⎮ x  dx
⌡
>>> exit()
```

After above steps run the python command again and I start getting errors.

## P.C. Specifications
```asciidoc
Device type :: Laptop
CPU :: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
RAM :: 8gigs
OS :: Windows 10 Home
PythonVer :: 3.9.2
```

I m not sure but the error might be because of `for line in open(filename, 'r'):` Changing it --to-> `for line in open(filename, 'r', encoding = "utf8"):` might work?

**Comment by adhxtry** [comment]
For anyone who is suffering with the same change the line 82 of `history.py` to `for line in open(filename, 'r', encoding = "utf8"):` and it worked.

**Comment by eabase** [comment]
>  change the line 82

Probably need to be changed in other lines as well, for full utf-8 support.

**Comment by brgirgis** [comment]
> For anyone who is suffering with the same change the line 82 of `history.py` to `for line in open(filename, 'r', encoding = "utf8"):` and it worked.

Please create a PR in the pyreadline3 repository, https://github.com/brgirgis/pyreadline3, and we can do a quick release.

**Comment by brgirgis** [comment]
Please send your PR [here](https://github.com/pyreadline3/pyreadline3)
