### ISSUE TITLE
I have discovered a code error

### ISSUE THREAD

**Issue by Momoha666** [pyreadline/pyreadline#85]
an error occured when i was trying to run a code with that package.

`Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site.py", line 446, in register_readline
    import readline
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\main.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\main.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\Moha\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'`

it's related to this file `py3k_compat.py` when i investigated it i realised that on line 8 in `py3k_compat.py` the script `return isinstance(x, collections.Callable)` was incorrect and the correct script is `return isinstance(x, collections.abc.Callable)`

Here is an image of where the error is located:
![Code_V57ZNkHYTW](https://github.com/user-attachments/assets/78734cf1-6de7-4ea6-ada2-fe1267683841)

**Comment by KrisTHL181** [comment]
look for [this ](https://github.com/pyreadline/pyreadline/pull/78)
this project is not in active development after 2022.
